### ISSUE TITLE
Создать компонент LocationMap.tsx II

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#100]
Задача 
1. В папке pages > Location> создаем папку components (если еще не создана) > далее папку нашего компонента LocationMap > и там уже LocationMap.tsx и LocationMap.scss (стараемся меньше inline стилей и больше записывать их в scss файл)
2. Так как карта будет содержать много чего, наверное лучше, чтоб это было отдельным компонентом, которая представляет из себя:
![31](https://user-images.githubusercontent.com/70585151/125195068-d820a080-e275-11eb-9a2a-8aa629e29efc.png)

3. Страница не должна иметь скрола (если скролить то уже идет взаимодействие с картой) и карта + хедер = 100% высоты и ширины страницы
4. На последнем сошлись, что будем вставлять карту Яндекса (нашел чуть документами https://yandex.ru/dev/maps/jsapi/) + много инфы есть в инете
5. Подключить компонент в Location.tsx (в Location.tsx должна быть оставлена подсказка куда вставить компонент)

Пока давайте просто вставим карту и посмотрим как это визуально будет

Мотивация
Интерактивная часть страница Location.tsx

Критерии приемки
Создан компонент и вставлен в location.tsx

Планируемое время работы
2 часа

**Comment by mkonevgit** [comment]
Фактическое затраченное время работы 1.5 часа

**Comment by mkonevgit** [comment]
Тикет был открыт заново с целью оставить комментарий о фактическом затраченном времени работы
