### ISSUE TITLE
Проверка запускаемых процедур после коммита

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#101]
Ниже в комментариях можете оставить скрины, что у вас происходит после git commit

Пример:
1. Создаем тестовую ветку git checkout -b test
2. Проверяем что мы в тесте git checkout
3. Изменяем любой .ts или .tsx файл (я всегда где то вставляю консоль лог и все)
![32](https://user-images.githubusercontent.com/70585151/125195331-fc30b180-e276-11eb-9c5d-65e66eee7d45.png)

4. git add .
5. git commit -m"test"
![33](https://user-images.githubusercontent.com/70585151/125195373-1e2a3400-e277-11eb-826d-9b73c76e2206.png)

Не важно фронт или бэк, все будет как на скрине, если у вас такого нету, то это не круто. В комментариях оставляйте, чтоб было видно коммит и действия после коммита.

Посмотрим что как и у кого

**Comment by 13IEZ** [comment]
Пример коммента 
![33](https://user-images.githubusercontent.com/70585151/125195430-634e6600-e277-11eb-9fcf-521072b3037c.png)

**Comment by DianaIsseyeva** [comment]
у меня на фронте вот так

![image](https://user-images.githubusercontent.com/68477832/125200573-8f74e180-e28d-11eb-9bc0-b5b50b0ed382.png)

**Comment by pashulia** [comment]
у меня все как и раньше....
https://prnt.sc/1aawcyh
