### ISSUE TITLE
Переписать компонент AppToolbar под новый дизайн

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#118]
Задача
Переписать компонент AppToolbar под новый дизайн.

Дополнительно
Размер компонентов в AppToolbar должны соответствовать дизайну (дизайн пакет находиться в архивариусе нашей группы)
Ссылка на лого так-же находится в архивариусе
Ссылки на соцсети и номер телефона игнорируем
Кнопки "Карта локаций" и "Магазин" оставляем по центру
Так-же как и раньше должны отрабатывать user-menu(user-icon, user-email) и anonymous-menu(регистрация и войти) 
При наведении на user-icon должны выпадать user-menu(личный кабинет и выйти) 
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Быть модным и красивым)

Критерии приемки
Должен быть переписан компонент AppToolbar в соответсвии с новым дизайном.

Планируемое время работы
2 часа
Фактическое время выполнения
2 часа

**Comment by Dauren3310** [comment]
В данной задаче не реализована адаптивность. 
Адаптивность AppToolbara перенесена на другой тикет
