### ISSUE TITLE
Создать страницу регистрации пользователя

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#12]
Конечный результат
В папке src/containers/Register создан файл Register.ts

План решения
В работе необходимо использовать AntDesign.
В папке src/containers/Register создать файл Register.ts , в нем должны быть:
I. прописаны следующие поля для ввода:
      1) username
      2) email
      3) phone
      4) password
II.  Кнопка для отправки формы

Мотивация
Пользователь сможет зарегистрироваться

Критерии приемки
В папке src/containers/Register создан файл Register.ts , в нем:
I. прописаны следующие поля для ввода:
      1) username
      2) email
      3) phone
      4) password
II.  Кнопка для отправки формы

Планируемое время работы
1 час

**Comment by Dauren3310** [comment]
Планируемое время работы: 1 час
Фактическое время работы: 2 часа
