### ISSUE TITLE
Создать компонент GlampingPros.

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#120]
Задача
Создать компонент GlampingPros в соответсвии с дизайном.

Дополнительно
Размер компонентов и их расположение должны соответствовать дизайну (дизайн пакет находиться в архивариусе нашей группы)
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Быть модным и красивым)

Критерии приемки
Должен быть создан компонент GlampingPros в соответсвии с дизайном

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 2 часа
