### ISSUE TITLE
Создать компонент "мини-магазин" в соответсвии с дизайном

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#121]
Задача
Создать компонент мини-магазин в соответсвии с дизайном, где будут отображаться 4 карточки (новинки) модулей на продажу.

Дополнительно
Размер компонентов и их расположение должны соответствовать дизайну (дизайн пакет находиться в архивариусе нашей группы)
Кнопка "Заказать" должна вести на страницу магазина (возможно кнопка будет переименована на "Подробнее" и вести будет на соответствующую страницу.)
Данные для отображения брать с фикстур бэка.
Прописать логику отображения последних четырех модулей на продажу(для бэка будет отдельный тикет для этой логики)
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Быть модным и красивым)

Критерии приемки
Должен быть создан компонент мини-магазин в соответсвии с дизайном

Планируемое время работы
4 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 4 часа
