### ISSUE TITLE
Создать компонент "мини-локации"

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#122]
Задача
Создать компонент "мини-локации" в соответсвии с дизайном, где будут отображаться 4 карточки (новинки) земля  в аренду.

Дополнительно
Размер компонентов и их расположение должны соответствовать дизайну (дизайн пакет находиться в архивариусе нашей группы)
Кнопка "Снять" должна вести на страницу Карта-локаций (возможно кнопка будет переименована на "Подробнее" и вести будет на соответствующую страницу.)
Данные для отображения брать с фикстур бэка.
Прописать логику отображения последних четырех участков земли для аренды(для бэка будет отдельный тикет для этой логики)
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Быть модным и красивым)

Критерии приемки
Должен быть создан компонент мини-локации в соответсвии с дизайном

Планируемое время работы
4 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 6 часов
