### ISSUE TITLE
Переписать компонент AboutUs под новый дизайн.

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#123]
Задача
Переписать компонент AboutUs под новый дизайн.

Дополнительно
Размер компонентов и их расположение должны соответствовать дизайну (дизайн пакет находиться в архивариусе нашей группы)
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Быть модным и красивым)

Критерии приемки
Должен быть переписан компонент AboutUs в соответсвии с новым дизайном

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
данный тикет выполнен в рамках тикета 125
