### ISSUE TITLE
Перенести папку ProductDetailGallery.

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#126]
Задача:
Перенести папку ProductDetailGallery из папки Store > components в соответствии с указаниями в тиките#92 (В папке pages > ProductDetail > создаем папку components (если еще не создана) > далее папку нашего компонента ProductDetailGallery > и там уже ProductDetailGallery.tsx и ProductDetailGallery.scss (стараемся меньше inline стилей и больше записывать их в scss файл))

Мотивация
Каждый компонент должен находиться на своем месте для простоты нахождения и редактирования в случае необходимости.

Критерии приемки
Папка ProductDetailGallery должна находиться в папке pages > ProductDetail > components 

Планируемое время работы
1 час

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 1 час
