### ISSUE TITLE
Создать страницу для аутентификации пользователя (Login)

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#13]
Конечный результат
В папке src/containers/Login создан файл Login.ts

План решения
В работе необходимо использовать AntDesign.
В папке src/pages/Login создать файл Login.ts , в нем должны быть:
I. прописаны следующие поля для ввода:
1) username
2) password
II. Кнопка для отправки формы

Мотивация
Пользователь сможет залогиниться

Критерии приемки
В папке src/containers/Login создан файл Login.ts , в нем:
I. прописаны следующие поля для ввода:
1) username
2) password
II. Кнопка для отправки формы

Планируемое время работы
1 час

**Comment by pashulia** [comment]
total time 40 min
