### ISSUE TITLE
Прописать кнопку "наверх".

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#136]
Задача: 
Прописать кнопку "наверх" которая будет будет по клику переносить на самый вверх страницы. Прописать логику для кнопки. На просторах инета имеется масса способов (например тут: https://qna.habr.com/q/68874)

Мотивация:
Для удобства пользования и быстрой прокрутки страницы вверх.

Критерии приемки:
На странице в любом положении в правом нижнем углу должна быть кнопка "наверх" (макет кнопки имеется в дизайн-макете, кнопка прорисована в правом нижнем углу блока "карусель, https://prnt.sc/1dsufzv)

**Comment by 13IEZ** [comment]
Тикет выполнен примерно за 4 часа (дополнительно был переделан компонент карусели и обновлен 1 блок на главной странице)
