### ISSUE TITLE
Создать блок AboutApp

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#148]
Задача 
Создать блок AboutApp, расположить на главной странице после карусели

Мотивация
Пользователь сможет ознакомиться с описанием приложения

Критерии приемки
Создан блок AboutApp, расположен на главной странице после карусели

Планируемое время работы
2 часа.

**Comment by pashulia** [comment]
требуется доработка после выбора стиля для карточки!
прописал четыре вида стиля для карточек!
время на разработку 3 часа, связанно с выбором стиля
дизайн взят из библтотеки https://ant.design/
