### ISSUE TITLE
Подключить сортировку по категориям модулей в Store

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#152]
Задача
Реализовать сортировку модулей по категориям (верхняя горизонтальная сортировка) в компоненте Store.
При нажатии на определенную категорию, должны отображаться модули соответствующей категории, в отображении использовать фикстуры.

Мотивация
Пользователь сможет просмотреть модули по выбранной категории

Критерии приемки
При нажатии на определенную кнопку категорий, отображаются модули соответствующей категории

Предполагаемое время выполнения: 4 часа

Фактическое время выполнения: 4 часа

**Comment by 13IEZ** [comment]
Сортировка происходит путем отправки query параметров на сервер. Параметры ловит сервер формирует массив и высылает на фронт (в url обязательно должны отражаться эти query параметры). Задача также связана с тикетом #157 потому что первый query параметр будет какая эта страница
