### ISSUE TITLE
Подключить боковую сортировку в Store (по данным указанным в StoreSidebar) 

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#153]
Задача
Подключить боковую сортировку в Store(по данным указанным в StoreSidebar) 

Мотивация
Пользователь сможет отсортировать нужные ему данные

Критерии приемки
При нажатии на кнопки боковой сортировки, отображаются модели в соответствии с выбранной опцией

**Comment by 13IEZ** [comment]
Сортировка происходит путем отправки query параметров на сервер, по которым фильтруются данные и на фронт приходит 100% готовый массив (query параметры должны отражаться в url адресе)
