### ISSUE TITLE
Создать блок GlampingMini

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#154]
Задача
Создать и вывести на главную страницу блок GlampingMini
За основу взять дизайн блока LocationMini
Блок должен содержать 4 карточки товара, ссылку "Показать на карте" и "Показать все"
Карточка товара должна содержать:
- картинку товара, 
- название
- расположение(как в блоке LocationMini)
- цену аренды
- рейтинг
- кнопку "Бронировать", при нажатии на которую происходит переход на страницу всех глэмпингов.
Ко всем ссылкам и кнопкам подключить функционал перехода на соответствующие страницы

Мотивация
Пользователь сможет вкратце ознакомиться с существующими глэмпингами

Критерии приемки
На главной странице после карусели расположен блок GlampingMini с содержимым, указанным в задаче.

**Comment by 13IEZ** [comment]
не вижу смысла создавать 3 блок, который ведет ровно туда куда и "локации"
