### ISSUE TITLE
В блоке LocationMini убрать кнопки "участки" и "кэмпинг" 

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#155]
Задача
На главной странице в блоке LocationMini убрать кнопки "участки" и "кэмпинг"

Мотивация
Отсутствие дублирующих ссылок

Критерии приемки
На главной странице в блоке LocationMini отсутствуют кнопки "участки" и "кэмпинг"

**Comment by 13IEZ** [comment]
Тикет закрыт в рамках тикета #158 part 2
