### ISSUE TITLE
Переделать карусель в карточке товара ProductDetailGallery

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#156]
Задача
Переделать карусель в карточке товара ProductDetailGallery, чтобы происходила смена картинок

Мотивация
Пользователь сможет просмотреть картинки конкретного товара

Критерии приемки
В карточке товара ProductDetailGallery работающая карусель

**Comment by 13IEZ** [comment]
Задача выполнено около 4 часов
