### ISSUE TITLE
Подключить пагинацию на странице Store

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#157]
Задача
Подключить получение и отображение товаров при нажатии на кнопки пагинации по 15 товаров

Мотивация
Товар приходит с сервера частями, обеспечив оптимизацию работы приложения 

Критерии приемки
При нажатии на кнопки пагинации, должен происходить запрос на сервер следующих 15 товаров и отображение их на соответствующей странице.

**Comment by 13IEZ** [comment]
При заходе в магазин с сервера приходит информация по первым карточкам + количество страниц (из расчёта сколько у нас в принципе итемов в базе) потом при переходе на след страницу меняется query параметр page=2 сервер ловит этот параметр и отправляет следующие итемы и т.д.
