### ISSUE TITLE
Переделать блок AboutApp в соответствии с  дизайном

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#171]
Задача
Переделать блок AboutApp на главной странице в соответствии с дизайном

Мотивация
Вид соответствует дизайну и выглядит в едином стиле

Критерии приемки
На главной странице блок AboutApp выглядит как на дизайне

Планируемое время 30 минут

**Comment by pashulia** [comment]
total time 30 min
