### ISSUE TITLE
Пофиксить bug отображения данных

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#176]
Задача
Реализовать корректное отображение данных на главной странице и в каталоге, с учетом пагинации и реализованных фильтров

Мотивация
Корректная работа приложения

Критерии приемки
На главной странице отображены все блоки, на странице каталога (магазина) отображены данные, работает пагинация и фильтры (по цене, по категориям)

**Comment by pashulia** [comment]
Total time 60 min
