### ISSUE TITLE
Внести изменения в App.ts (подключить панель навигации)

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#18]
Конечный результат
В файле App.ts : 
1) выводится панель навигации (AppToolbar)
2) Подключены route на страницы регистрации ("/register") и аутентификации ("/login")

План решения
В файле App.ts : 
1) в разметку внести компонент AppToolbar
2) Подключить Route на страницы регистрации ("/register") и аутентификации ("/login")

Мотивация
Пользователь сможет пользоваться панелью навигации и перейти на страницу регистрации и/или аутентификации

Критерии приемки
1) На главной странице отображена панель навигации
2) При нажатии на кнопку Sign Up пользователь попадает на страницу регистрации ("/register")
3) При нажатии на кнопку Sign In пользователь попадает на страницу аутентификации ("/login")

Планируемое время работы
30 минут

**Comment by 13IEZ** [comment]
Фактически затраченное время - 2 часа
