### ISSUE TITLE
Разработать страницу размещений модулей (или глэмпингов)

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#186]
Задача
Создать страницу, отображаемую список глэмпингов при щелчке на флажке локации на карте.

В создании страницы участвуют модели: Product, Accomodation, Pich, Category

Новые фикстуры с новыми и измененными моделями в файле fixtures-code.js и новые модели в файлах
Accomod.js и Pich.js выложены в общий чат

Примерная структура страницы.
1. Карусель из изображений локаций вверху. Данные по карусели запрашивать из изображений локаций. 
2. Карточки глэмпингов. Верхняя часть, изображение модуля, запрашивать из поля image модели Accomod

3. Информация по глэмпингу. 
Первое поле
Используя поля roominess из модели Product и title схемы Category составить для отображения на странице предложение типа "Название модуля (поле title) на 6 (поле roominess) человек".  
Второе поле
Поле description из модели Accomod в котором будет описательная информация типа "Прекрасное место лес, рядом речка, проведено электричество, есть подъезд и место для машины"

План выполнения работы:
1. Используя роут, разработанный в тикете 94 на бэке, содать функционал редюсера 
для страницы глэмпингов на фронте
2. Создать компоненты для отображения данных на странице
3. Страница глэмпингов для данной локации должна выводится по щелчке на флажке локации в карте или по щелчке на карточке локаций из каталога локаций из тикета 189

Мотивация
Разработать страницу размещений модулей (или глэмпингов)

Критерии приемки
Работа функционала без ошибок при тестировании тикета

Планируемое время работы 
4 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 5 часов
