### ISSUE TITLE
Разработать страницу, выводящую список piches как генеральный план участка

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#187]
Задача
Разработать блок на странице "Глампинги"(CurentLocation), выводящую список всех piches.

В заголовке pich ставить ее номер

1. Каждый pich оформить в виде карточки с картинкой и текстовыми полями 
1.1 Номер pich и ее наименование в ее заголовке (поля number и title модели Pich)
1.2 Картинку в ее верхней части (поле image)
1.3 Ее описание в нижней части (поле description)
1.4 Кнопку "Подробнее" для перехода на страници CurentPich.
2. Под списком piches внизу вывести итоговую информацию, показывающую сколько занято, а сколько свободно piches.
3. Генеральный план добавить в карусель картинок.

Мотивация
Используя термины заказчика вывести генеральный план участка

Критерии приемки
Работа функционала без ошибок при тестировании тикета

**Comment by 13IEZ** [comment]
Данный комментарий также является обязательным к исполнению:

1. BG-color замкнут в рамки контейнера (так быть не должно), либо сделайте страницу белую, либо оставьте текущий цвет но избавьтесь от рамки (в контейнере лежит только контент)
![image](https://user-images.githubusercontent.com/70585151/128623092-ad2eba61-6eef-4a30-958b-76bf5ad9c29c.png)

2. В карусели включите функцию, чтоб были видны стрелочки (функция прям в компоненте)
3. Карточки пичи/акком, на карточке Pich должна быть кнопка "бронировать" на карточке акком кнопка "подробнее". 
4. Так как в карточке будут кнопки нужно переделать, чтоб вся карточка не была кликабельна а только кнопка в ней 
5. Кнопки в карточке по дизайну как на главной странице с блока "локации, магазин"
