### ISSUE TITLE
Заполнить карточку товаров реальными данными

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#192]
Задача
Заполнить карточку товаров реальными данными
1. Обновить файл fixtures-code.js последняя версия которого добавлена в общий чат. Выполнить его. В файле созданы по несколько экземпляров Review для для одного Location и Product. Сделано для того, чтобы можно было реализовать функционал расчета рейтинга как среднее арифметическое оценки по экземплярам Review.
2. Поля моделей данных товаров для обновления (сверху вниз)
2.1 Поле title модели Product
2.2 Среднеарифметическое рейтинга для данного productId, подсчитанное по всем экземплярам Reviews. Для этого на бэке создан get запрос по productId в тикете 100. 
2.3 Среднеарифметическое рейтинга выводится в виде соотв. количества звездочек
2.4 Убрать ссылку (30 отзывов). Добавить количество отзывов во вкладку Отзывы 
2.5 Цена поле price модели Product
2.6 Описание поле description модели Product
2.7 Карточку продукта стилизовать в соотв. с макетом от KASPI выложенным в общий чат

Мотивация
Заполнить карточку товаров реальными данными

Критерии приемки
Работа функционала без ошибок при тестировании

Статьи по реализации звездного рейтинга в React
Хорошие статьи
https://ichi.pro/ru/kak-ispol-zovat-css-i-react-dla-sozdania-zvezdnogo-rejtinga-101140130179867
https://question-it.com/questions/2952669/komponent-rejtinga-react-star

Планируемое время работы
1 час

**Comment by DianaIsseyeva** [comment]
на тикет потрачен 1 час
