### ISSUE TITLE
Создать карточку пичи

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#215]
Задача 
1) Реализовать отображение пичи со следующим содержимым:
      1. Номер отображаемой пичи
      2. Картинка плана участка
      3. Селект со списком всех моделей магазина и дополнительным вариантом - другое
          3.1. если выбран вариант другое - открывается форма со следующими полями:
                 - Категория (селект)
                 - Сезон (селект)
                 - Вместимость (селект)
                 - Описание
                 - Картинки (прикрепить)
      4. Календарь (как вариант - Datepicker в AntDesign)
      5. Кнопка подать заявку
2) Реализовать логику отправки заполненных данных на сервер

Мотивация
Потенциальный инвестор сможет выбрать пичу и отправить заявку на ее бронирование

Критерии приемки
Отображается карточка пичи, с содержимым указанным в задаче

**Comment by pashulia** [comment]
Total time 120 min
