### ISSUE TITLE
Подключить пагинацию на странице "локации".

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#231]
Задача
Подключить получение и отображение локаций при нажатии на кнопки пагинации по 15 товаров

Мотивация
Локации приходит с сервера частями, обеспечив оптимизацию работы приложения

Критерии приемки
При нажатии на кнопки пагинации, должен происходить запрос на сервер следующих 15 товаров и отображение их на соответствующей странице

Планируемое время работы
1 час

**Comment by DianaIsseyeva** [comment]
на тикет потрачен 1 час

**Comment by pashulia** [comment]
limit = 15, нужно исправить, при добавлении сайдбара с фильтрами в одном ряду будет по 3 карточки, по этому нам нужно на одной странице 15 айтимев
