### ISSUE TITLE
Создать страницу "Accommodations".

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_front#233]
Задача:
Создать страницу "Accommodations".

Критерии приемки:
На главной странице приложения есть блок "AccommodationsMini" с кнопкой "показать всё", нажимая на неё мы переходим на страницу "Accommodations" где отображаются карточки с готовыми "accommodations". 
Прописать на странице пагинацию.
Прописать на странице сайдбар с фильтрами.

Мотивация:
Дать возможность юзеру посмотреть все возможные Аккоммо

Планируемое время:
3 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 5 часов
