### ISSUE TITLE
Инфа о развлечениях и удобствах в Глэмпинг (после тикета 141 на бэке)

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#265]
Задача
Поставить Инфу о развлечения и удобствах который имеет глэмпинг на странице  о глэмпинге (локации) после поля description.
Также сделать разделение блоков с пичами и аккомодашэнами как говорил заказчик на последней встрече. 

Критерии приемки
На странице о глэмпинге есть инфа о развлечения и удобствах

Планируемое время работы
1 час

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 3,5 часа
