### ISSUE TITLE
Создать компонент-шапку

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#31]
Задача
Создать компонент-шапку в которой будут следующие элементы:
Logo 
номер телефона 
адрес электронной почты
знак facebook
знак instagram
кнопка бронировать
надпись RU говорящая на каком языке сейчас сайт
ссылка на страницу логина
ссылка на страницу регистрации

Дополнительно
Необходимые картинки и  значки которые вы не найдете в ant design можно брать и интернете на свое усмотрение.
Мокап шапки и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first) 
На кнопки и ссылки можно временно навесить заглушки. Для ссылок - #. Для кнопок console.log

Мотивация
Иметь панель в которой можно взаимодействовать с функциями приложения

Критерии приемки
Должен быть создан рабочий компонент-шапка выглядящий как на мокапе 

Планируемое время работы
3 часа

**Comment by 13IEZ** [comment]
Шапка была сделана согласно новому макету. Так как у нас еще нету понимания как будет все выглядеть в мобильной версии верстка сделана (как во всех компонентах) desktop first. Затраченное время около 4 часов.
