### ISSUE TITLE
Создать компонент слайдер

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#32]
Задача
Создать компонент слайдер  в котором может находиться несколько картинок от 3 до 8

Дополнительно
Слайдер должен сам перелистывать фотографии через какой-то интервал времени (пару секунд) и также сам пользователь тоже может это делать.
Размер слайдера расчитывайте на глаз сами. (пока у нас только мокап, макет предоставят в будущем)
Необходимые картинки для слайдера можете взять в интернете для примера.
Мокап слайдера и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Завлечь клиентов.

Критерии приемки
Должен быть создан рабочий компонент слайдер 

Планируемое время работы
2 часа

**Comment by 13IEZ** [comment]
Фактически затраченное время около 1.5 часов, карсуель получилось достаточно адаптивная до 370 Px (но при уменьшении нужны соответствующие картинки)
