### ISSUE TITLE
Создать компонент с вкладками - карта и модули

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#33]
Задача
Создать компонент с вкладками - карта и модули

Дополнительно
При переходе на определенную вкладку - это вкладка должна быть подсвечена.
Мокап компонента с вкладками и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Предоставить удобное взаимодействие с приложением    

Критерии приемки
Должен быть создан рабочий компонент с вкладками

Планируемое время работы
1 час

**Comment by 13IEZ** [comment]
Как понимаю тикет был выполнен в рамках тикетах #31
