### ISSUE TITLE
Создать компонент-блок "О нас"

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#34]
Задача
Создать компонент-блок "О нас" в котором будет текст - информация о компании и карточки тех кто является главными лицами этой компании. 

Дополнительно
В качестве текста можете использовать рыбный текст или взять его с сайта glamping.kz
В качестве картинок можете использовать какие-нибудь картинки заглушки или взять их с сайта glamping.kz
Размер текста и карточек расчитывайте на глаз сами. Главное что бы было гибко - то есть можно было добавить текста и  убавить его, тоже самое и с карточками. (пока у нас только мокап, макет предоставят в будущем)
Мокап блока "О нас" и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Рассказать о компании

Критерии приемки
Должен быть создан рабочий компонент-блок "О нас"

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 1,5 часа
