### ISSUE TITLE
Создать компонент-блок - "стать инвестором"

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#35]
Задача
Создать компонент-блок - "стать инвестором" в котором будет 
1)текст который расскажет что такое glamping 
2)кнопка - "Стать инвестором"
3)список от том что входит в обычный кемпинг
3)список о том что входит в глэмпинг

Дополнительно
Над каждым списком должна быть картинка (кемпинга или глэмпинга)
Для кнопки можете создать заглушку в виде console.log
Размер компонента  расчитывайте на глаз сами. (пока у нас только мокап, макет предоставят в будущем)
Необходимые картинки или значки если понадобятся можете взять в интернете для примера.
Мокап компонента-блока  и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Завлечь инвесторов.

Критерии приемки
Должен быть создан рабочий компонент-блок "стать инвестором"

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 1,5 часа
