### ISSUE TITLE
Создать компонент-блок "сдать землю"

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#36]
Задача
Создать компонент-блок "сдать землю" в котором будет 
1)текст предлагающий сдать землю в аренду
2)кнопка - "Сдать землю в аренду"
3)картинка 

Дополнительно
Для кнопки можете создать заглушку в виде console.log
Размер компонента расчитывайте на глаз сами. (пока у нас только мокап, макет предоставят в будущем)
Необходимые картинки или значки если понадобятся можете взять в интернете для примера.
Мокап компонента-блока "сдать землю"  и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Завлечь владельцев земли к сделке.

Критерии приемки
Должен быть создан компонент- блок "сдать землю"

Планируемое время работы
1 час

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 1,5 часа
