### ISSUE TITLE
Создать компонент с отзывами

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#37]
Задача
Создать компонент с отзывами в котором будет
1 карточки в которых будет
1.1 аватар человека который написал отзыв
1.2 Имя человека
1.3 Отзыв человека

Дополнительно
Размер компонента и карточек расчитывайте на глаз сами. (пока у нас только мокап, макет предоставят в будущем)
Необходимые картинки или значки если понадобятся можете взять в интернете для примера.
Мокап компонента-блока с отзывами и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Убедить к сделке инвесторов

Критерии приемки
Должен быть создан компонент с отзывами

Планируемое время работы
2 часа

**Comment by pashulia** [comment]
total time 30 min
