### ISSUE TITLE
Создать компонент Footer

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#38]
Задача
Создать компонент с отзывами в котором будет
1 Ссылки на следующие страницы
1.1 Страницу посвященные инвесторам
1.2 Страницу посвященные туристам 
1.3 Страницу посвященные арендтодателям
2 Адрес офиса
3 номер контактного телефона
4 адрес эл почты
5 Ссылки в виде значков на следующий страницы:
5.1 Страницу facebook
5.2 Страницу инстаграмм

Дополнительно
Размер компонента Footer расчитывайте на глаз сами. (пока у нас только мокап, макет предоставят в будущем)
Необходимые картинки или значки если понадобятся можете взять в интернете для примера.
Мокап компонента Footer и всего приложения лежит в группе телеграмм - там можно посмотреть расположение элементов.
Для ссылок можете оставить заглушку в виде #
Все компоненты должны быть адаптивными (Mobile first)

Мотивация
Оставить данные для связи с компанией

Критерии приемки
Должен быть создан компонент Footer

Планируемое время работы
2 часа

**Comment by 13IEZ** [comment]
Фактически затраченное время около 1 часа.
