### ISSUE TITLE
Сделать главную страницу адаптивной

### ISSUE THREAD

**Issue by Dauren3310** [13IEZ/glamping_front#57]
Задача:
Сделать главную страницу адаптивной. Все компоненты которые находятся в компоненте Main необходимо сделать адаптивными под планшеты, телефоны  и для мониторов с разрешением 4к и выше.

Дополнительно:
Желательно сделать адаптивность по методу Mobile First. Но в целом детали реализации не важны.

Мотивация:
Больше половины пользователей используют телефон для выхода в интернет. Поэтому нам нужно сделать так, чтобы использование нашего приложения было удобно со всех устройств, особенно с мобильных.  

Критерии приемки:
При уменьшении и увеличивании экрана компоненты: 
- не наезжают друг на друга
- не появляется горизонтальный стролл
- все компоненты выглядят соразмерно

Предполагаемое время выполнения: 3 часа.

**Comment by 13IEZ** [comment]
Фактически затраченное время около 6 часов
