### ISSUE TITLE
Создать компонент выводящий список товаров

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#68]
Задача
1. Создать компонент выводящий список товаров
Элемент списка товара должен состоять из
1.1. Изображения товара
1.2. Наименования товара
1.3. Описание товара
1.4. Цены
1.5. Кнопки подробнее выводящей на страницу детальной информации о товаре
2. Реализовать сортировку элементов списка по типу, наименованию и цене
3. Реализовать пагинацию для элементов списка
Дополнительно
Размер и компоновку элементов списка смотреть в мокапе
Размер и компоновку кнопок сортировки смотреть в мокапе
Размер и расположение элементов пагинации смотреть в мокапе

Мотивация
Вывести список товаров для покупателя

Критерии приемки
Должен быть создан компонент выводящий список товаров

Планируемое время работы
6 часов

**Comment by pashulia** [comment]
total time 4 hours
