### ISSUE TITLE
Создать компонент выводящий детальную информацию о товаре

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#69]
Задача

1. Создать компонент выводящий детальную информацию о товаре
Компонент должен состоять из
1.1. Изображений товара
1.2. Описания товара
1.3. Описание базовой комплектации
1.4. Дополнительного описания (электроника, безопасность и.т.д)
1.5. Описания технических характеристик
1.6. Кнопки Заказать, открывающей страницу заказа
1.7. Заголовка и изображений сертификатов, если таковые имеются
Дополнительно
Размер и приблизительную компоновку элементов страницы можно посмотреть в мокапе
При отсутствии сертификаты не выводить
2. Создать страницу заказа для выбранного товара
Компонент должен состоять из
2.1. Наименования и данных выбранного объекта в заголовке (подгружаются автоматически)
2.2. Имя заказчика
2.3. Фамилия заказчика
2.4. Электронный адрес
2.5. Номер сотового телефона
2.6. Кнопки Далее выводящей окно платежной системы
Дополнительно
Размер и приблизительную компоновку элементов страницы можно посмотреть в мокапе
Все поля сделать обязательными для заполнения

Мотивация
Вывести детальную информацию о товаре для покупателя

Критерии приемки
Должен быть создан компонент детальной информации о товаре

Планируемое время работы
6 часов

**Comment by Dauren3310** [comment]
Этот тикет выполнил Павел
