### ISSUE TITLE
Обернуть фронтенд и бакенд часть в докер-контейнеры и развернуть на Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#71]
Задача
Обернуть фронтенд и бакенд часть в докер-контейнеры и развернуть на Linux Ubuntu 20.04
Задачу разбить на следующие этапы:
1. Установить docker и docker-compose на Linux Ubuntu 20.04
2. Клонировать бакенд и фронтенд проекта на Linux Ubuntu 20.04 из github
3. Настроить на бакенде файл docker-compose.yml для организации взаимодействий контейнеров бакенда и mongodb
4. Запустить контейнеры, выполнить fixtures.js, и протестировать взаимодействие бакенда и базы
5. Настроить на фронте файл Dockerfile для запуска контейнера с фронтендом
6. Выполнить build контейнера и протестировать его взаимодействие с бакендом
7. Составить подробный отчет по которому можно произвести вышеописанные действия

Мотивация
Освоить докер-технологию для развертывания приложения на хостинге для демонстрации заказчику

Критерии приемки
Отчет по проведенной работе

Планируемое время работы
8 часов

**Comment by 13IEZ** [comment]
Совокупно потрачено более 12 часов (+ еще время Михаила которое трудно оценить)
