### ISSUE TITLE
В форме регистрации добавить поля имя, фамилия и номер телефона

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#74]
Задача
Изменить форму регистрации добавить поля имя, фамилия и номер телефона

Мотивация
Задача поставлена, чтобы не делать отдельную форму для заполнения этих полей

Критерии приемки
В форме регистрации должны заполняться поля имя, фамилия и номер телефона с занесением в базу

Планируемое время работы
1 час

**Comment by Dauren3310** [comment]
Выполнил задачу по требованию.
Времени на выполнение задачи ушло слишком много потому-что пытался сделать поле -  phone строгим только для чисел и с черточками между пару чисел. В итоге не получилось.
Фактическое время выполнения: 3 часа
