### ISSUE TITLE
Использовать информацию из базы для компонента выводящего список товаров

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_front#75]
Задача
Использовать информацию из базы для компонента выводящего список товаров

Мотивация
Отобразить информацию из базы для компонента выводящего список товаров

Критерии приемки
Компонент должен выводить информацию из базы

Планируемое время работы
1 час

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 4 часа
