### ISSUE TITLE
Создать меню зарегистрированного пользователя (UserMenu.ts)

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_front#8]
Конченый результат
Создано меню для зарегистрированного пользователя (UserMenu.ts)

План решения
В папке src/components/UI/AppToolbar/Menus создать UserMenu.ts, в нем используя AntDesign отобразить кнопку Log out 

Мотивация
При необходимости пользователь может разлогиниться

Критерии приемки
При нажатии на кнопку на Log out, рендерится главная страница "/"

Планируемое время работы
1 час

**Comment by pashulia** [comment]
total time 120 min
