### ISSUE TITLE
Создать container и обернуть в него компоненты

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#81]
Задача
в index.scss добавить стили для контейнера (max-width = 1240px, margin = 0 auto, padding = 0 20px)
Каждый элемент страницы обернуть (кроме карусели) в div className='container' по аналогии со скрином
![1](https://user-images.githubusercontent.com/70585151/125161178-aa1e5c00-e1a2-11eb-8eb9-b343e1cafa09.png)

Если у вас есть идея лучше и проще как это произвести без дополнения всего доп дивом, то можете мне написать и обсудим, но пока самый легкий и самый безболезненный вариант вижу такой.

Мотивация
Исправится баг, при котором страница растягивается на любое разрешение и будет строго иметь 1240px 

Критерии приемки
Все компоненты обернуты в дополнительный dive container

Планируемое время работы
2 часа

**Comment by pashulia** [comment]
total time 90 min
