### ISSUE TITLE
Поменять название кнопки

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#82]
Задача
Поменять название кнопки, в хедере, на "Магазин"
![2](https://user-images.githubusercontent.com/70585151/125161302-5ceeba00-e1a3-11eb-8c1b-e3e7bb36c35f.png)

Мотивация
Просьба изменить название от заказчика

Критерии приемки
Кнопка должна называться "Магазин"

Планируемое время работы
30 минут

**Comment by Dauren3310** [comment]
фактическое время выполнения: 30 минут
