### ISSUE TITLE
Создания страницы "Магазин" / "Store" - (сделать в первую очередь)

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#83]
Задача (основная задача, это создать страницу контейнер куда будут подключать элементы страницы)
1. В папке pages переименовать  папку ModulesList в Store
2. Переименовать компонент из ModulesList.tsx в Store.tsx
3. В App.tsx изменить роут <Route path='/modules' exact component={ModulesList} /> в первую очередь пусть на /store, компонент изменить на Store.tsx
4. в AppToolbar.tsx линк пути /modules изменить на /store

Общий вид страницы, как вы видите она поделена на части, задача в рамках этого тикета это подготовить контейнер, в который будут подключаться элементы страницы
5. https://ant.design/components/layout/#header построение Layout, там есть второй вариант, который нам идеально подходит и имеет следующую структуру 
    <Layout>  --- уже обернуто нашим приложением
      div class=container
      <Header>наш хедер</Header> --- наш AppToolBar
      <Layout> Оборачиваем sidebar и контент часть и второй хедер
        <Sider>Вместо это вставь наш сайдер</Sider> --- отдельный тикет будет
        <Content> Здесь будут карточки клиентов</Content>   --- контентную часть надо рассчитать на 4 карточки в ряд и 4 в колонку потом пагинация
      </Layout>
      <Footer>Footer</Footer> --- футер удаляем он нам тут не нужен, пагинация будет помещена в контент
      div class=container
    </Layout>
Выше лишь пример с ant design

6. Логические разметьте где должны находиться какие элементы
![11](https://user-images.githubusercontent.com/70585151/125164543-a09def80-e1b4-11eb-86b3-ac29ec5d59ef.png)

7. Вставить рандомные карточки (например как у нас в отзывах), и посмотреть по размеру, чтоб были 4 в ряд и после переносились, каждая новая карточка появляется в самом начале с лево на право

Мотивация
Качественная структура облегчит подключение в нею компонентов

Критерии приемки
Выполнены все вышеперечисленные действия

Планируемое время работы
3 часа

**Comment by pashulia** [comment]
выполнил в этом тиките еще и тикет 84(случайно, увлекся) вертикально установить максимум 4 карточки не удалось, переполнение столбца в целом начнет новую компоновку строк. общее время 5 часов
