### ISSUE TITLE
Создать компонент StoreMenu.tsx  I

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#84]
Задача (сперва должна быть сделана задача https://github.com/13IEZ/glamping_front/issues/83)
1. В папке pages > Store > создаем папку components > далее папку нашего компонента StoreMenu > и там уже StoreMenu.tsx и StoreMenu.scss (стараемся меньше inline стилей и больше записывать их в scss файл)
2. Подключаем компонент в Store.tsx в место где должно находится меню
![4](https://user-images.githubusercontent.com/70585151/125162925-747e7080-e1ac-11eb-9eff-23859033b63f.png)

3. Меню представляет из следующее
![5](https://user-images.githubusercontent.com/70585151/125162949-94ae2f80-e1ac-11eb-829d-0d737d1cb820.png)

4. https://ant.design/components/layout/#header - есть примеры меню, меню должно быть в белом цвете
5. Должен иметь эффект при hover (визуально понятно, что это кликабельно)
6. Должен иметь эффект active (то есть если кликнул и увел мышку, видно, что кликал на это)
![6](https://user-images.githubusercontent.com/70585151/125163063-1b630c80-e1ad-11eb-8bab-58fe606049de.png)

Функционал меню (но пока делаем верстку):
1. При попадании на страницу Store.tsx появляются все элементы магазины 
2. При клике на один из элементов меню магазин будет фильтроваться по категории товаров (категории это элементы меню)
3. В идеале при клике на каждый элемент должно передаваться название элемента, по которому мы делаем запрос и рисуем новую страницу пользователю
*** но пока главное верстка на функционал будет отдельный огромный тикет, пока интересует верстка и заморачиваемся в рамках верстки

Мотивация
Создать важный элемент страницы Store.tsx

Критерии приемки
Вышеописанные требования (не относится к Функционалу, но важно, чтоб верстке это понимали и сделали максимум просто и удобно)

Планируемое время работы
2 часа

**Comment by pashulia** [comment]
total time 80min
