### ISSUE TITLE
Создать компонент StoreSidebar.tsx II

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#85]
Задача 
1. В папке pages > Store > components > создаем папку нашего компонента StoreSidebar> и там уже StoreSidebar.tsx и StoreSidebar.scss (стараемся меньше inline стилей и больше записывать их в scss файл)
2. Подключаем компонент в Store.tsx в место где должно находится sidebar
![7](https://user-images.githubusercontent.com/70585151/125163440-fe2f3d80-e1ae-11eb-9ec2-d80f03652488.png)

3. https://ant.design/components/layout/#Layout.Sider - полистайте вниз и найдете примеры использования sidebar ваш компонент это <Sider>ваш контент</Sider> его и экспортируете
4. Содержимое sidebar:
![10](https://user-images.githubusercontent.com/70585151/125164034-f0c78280-e1b1-11eb-97b7-4c6d192586d1.png)
5. Каждая позиция sidebar должна иметь эффект hover и active 
![9](https://user-images.githubusercontent.com/70585151/125163778-95e15b80-e1b0-11eb-9cac-2a5634415f41.png)
6. Цена: не могут быть выбраны сразу 2 элемента либо по возрастанию либо по убыванию (соответственно если был выбран по возрастанию и мы кликаем по убыванию то галочка снимается с возрастания и ставится на убывания)
7. Вместимость: могут быть выбраны несколько элементов (хоть все)
8. Сезонность: оба варианты могут быть кликнуты вместе (они могут быть как летние так и зимние)
9. Производитель: могут быть кликабельны все элементы
10. Категории: могут быть выбраны хоть все

Функционал:
Компонент будет очень сложный по функционалу но при верстке можно уже учитывать его
1. При клике мы получаем данные по чему именно кликнули и отправляем запрос на сервер, который фильтрует и собираем данные
2. Получаем готовый массив данных с сервера и отрисовываем 
3. Будет отдельные тикеты там уже будем все обдумывать как лучше фильтровать

Мотивация
Важный элемент страницы Store.jsx

Критерии приемки
Выполнены все вышеописанные требования к элементу, кроме Функционала)

Планируемое время работы
3 часа

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 2 часа
