### ISSUE TITLE
Создать компонент StoreItem.tsx III

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#86]
Задача
1. В src > components лежит папка ModuleCard, необходимо её переименовать в StoreItem.tsx (и папку соответственно) перенести в pages > Store > components (доработать имеющийся элемент)
2. Подключаем компонент в Store.tsx в место где должны находится карточки (в Store.tsx будут получены все элементы магазина и потом через .map будем по нему проходится и возвращать элемент StoreItem.tsx)
![12](https://user-images.githubusercontent.com/70585151/125164580-d7740580-e1b4-11eb-91fa-98607bc4aeeb.png)
3. Карточка из себя представляет следующие (мы определись, что вариант карточки kaspi.kz нам хорошо подходит)
![13](https://user-images.githubusercontent.com/70585151/125164693-4fdac680-e1b5-11eb-8ef8-b34e4bf65e83.png)
4. Карточка состоит из двух частей, из картинки сверху и снизу информацию (думаю для наглядности можно зайти и посмотреть непосредственно на Kaspi.kz)
5. https://ant.design/components/card/#header - примеры карточек там есть очень похожие как нам нужны
6. Важно, чтоб в ряд помещалось 4 карточки (при разрешении 1240px) потом следующая карточка переносится на новую строку и встает первая с лево на право
***посмотрите варианты с грид сеткой в анте
7. Каждая карточка является Link, которая при клике будет вести на страницу товара по пути /store/:id элемента

Функционал: пока еще бэк будет в процессе, поэтому можно заглушками 5-7 карточек разместить
1. Мы будем получать список всех элементов магазина
2. Потом будет через .map пробегаться по массиву и возвращать наш элемент StoreItem.tsx
3. StoreItem принимает в себя: название, цена, рейтинг, картинку (на превью, пока можно первую с массива, но в идеале на превью должна быть отдельная картинка), id

Мотивация
Важный элемент страницы Store.tsx

Критерии приемки
Выполнены все вышеописанные критерии (включая функционал)

Планируемое время работы
3 часа

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 3 часа
