### ISSUE TITLE
Создания страницы "ProductDetail" 

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#90]
Задача (задача создать контейнер страницы в которую будут подключаться компоненты страницы)

1. При клике на элемент находящийся в Store.tsx (карточка товара) пользователь идет по ссылке /store/:id где попадает на страницу товара
2. Необходимо обновить название компонента pages > ModuleInfo в pages > ProductDetail и соответствующий файл в нем
3. Не забываем обернуть страницу в div className = container
4. Изменить роут в App.tsx <Route path='/modules/info' exact component={ModuleInfo} />  в 
<Route path='/store/:id' exact component={ProductDetail} />
5. Структура страницы (все договорились, что нам хорошо подходит kaspi.kz)

![19](https://user-images.githubusercontent.com/70585151/125187052-806f3e80-e24f-11eb-893d-c140196b5cde.png)

6. В рамках тикета вы создаете структуру этой страницы, чтоб последующие подключенные компоненты ровно заняли свое место
7. Кнопка "купить" линк, но пока еще не определились куда именно будет вести кнопка
8. Сделать подсказки разрабам компонентов, где какой элемент должен лежать 

Мотивация
Создание страницы товара

Критерии приемки
Все выше описанные требования соблюдены, структура максимально соответствует нашему аналогу

Планируемое время работы
3 часа

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 2 часа 30 минут
