### ISSUE TITLE
Создать компонент ProductDetailDescription.tsx II

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#93]
Задача (задача зависит от выполнения #90)
1. В папке pages > ProductDetail > создаем папку components (если еще не создана) > далее папку нашего компонента ProductDetailGallery > и там уже ProductDetailDescription.tsx и ProductDetailDescription.scss (стараемся меньше inline стилей и больше записывать их в scss файл)
2. Компонент представляет из себя следующее 
![24](https://user-images.githubusercontent.com/70585151/125188309-443edc80-e255-11eb-9bd3-cdcc3d055ffc.png)

3. В целом вдохновляемся мы kaspi https://kaspi.kz/shop/p/apple-macbook-air-2020-13-3-mgn63-seryi-100797845/?c=750000000  
4. Чтоб создать логические разрывы между блока может помочь https://ant.design/components/divider/#header
5. После создания компонента пока можно наполнить его рандомной информацией тикеты на функционал будут позже
6. Подключить компонент в ProductDetail (разработчик ProductDetail должен оставить логическую подсказку куда именно его подключить)

***Примерный функционал:
1. Человек в Store кликаек на карточку клиента
2. Человек попадает ProductDetail  (куда подключен данный компонент)
3. Происходит запрос по конкретному товару, информация которая передается в компоненты 

Мотивация
Создание описания продукта

Критерии приемки
Выполнены все вышеописанные требования

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 2 часа
