### ISSUE TITLE
Создать компонент ProductDetailReviews.tsx III

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#96]
Задача (задача зависит от выполнения #90)

1. В папке pages > ProductDetail > создаем папку components (если еще не создана) > далее папку нашего компонента ProductDetailReviews > и там уже ProductDetailReviews.tsx и ProductDetailReviews.scss (стараемся меньше inline стилей и больше записывать их в scss файл)
2. Компонент из себя должен представлять следующие (то есть слева автор, оценка, дата. В правой части только комментарий, без достоинств, недостатков и т.д.)
![25](https://user-images.githubusercontent.com/70585151/125189190-abaa5b80-e258-11eb-8202-f57f090bc531.png)

Вопросы, которые стоит обсудить с ментором 13.07
1. Разбить компонент на еще более мелкие компоненты (ProductDetailReviewsItem)?
2. Получать в ProductDetail уже список всех комментариев и передавать их в ProductDetailReviews или в самом компоненты ProductDetailReviews их запрашивать?
3. Как быть если комментариев будет тысяча? Сделать пагинацию или просто путь идет полотно вниз со всеми комментариями?

Мотивация
Создание блока с комментариями к ProductDetail 

Критерии приемки
Выполнены все вышеописанные требования

Планируемое время работы
4 часа

**Comment by DianaIsseyeva** [comment]
данный тике не актуален, компонент изменил смысл и вид
