### ISSUE TITLE
Изменения стилей формы Регистрации и Авторизации 

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#97]
Задача
1. Выровнять страницу Авторизации по уровню страницы Регистрации
![26](https://user-images.githubusercontent.com/70585151/125189836-f4174880-e25b-11eb-8f07-2c20cbbb4c00.png)

2. Сделать страницы адаптивными до разрешения 320px (при разрешении <=480px кнопки "регистрация" и "войти" должны 

Мотивация
Эстетическое наслаждение от страниц

Критерии приемки
Они должны быть на одном уровне, и адаптированы

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
ищ тикета выполнен п.1, на его исполнение потрачено 30 минут
