### ISSUE TITLE
Создания страницы "Location"

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#98]
Задача 

1. В папке pages создаем папку Map и в ней компонент Map.tsx
2. Страница представляет из себя следующую структуру
![29](https://user-images.githubusercontent.com/70585151/125193919-c5f03380-e270-11eb-9106-243be7e8922a.png)

3. Создать соответствующий роут, который доступен любому пользователю  path='/location'
4. Страница не должна иметь скрола, хедер и карта занимают 100% визуальной части страницы (в div.container не оборачиваем) наш ориентир - https://www.camping.info/ru/%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B5?area=-24.873046,58.676937,59.501953,33.174342&zl=5&adults=2
5. В рамках тикетах только создаем структуру страницы, оставляем подсказки для разрабов компонентов что и где должно находиться 

Например (вы создаете скелет страницы, компоненты к странице могут делать другие разрабы):
 <Layout> - уже обернуто наше приложение
      <Header>Header</Header>  - наша шапка
      <Content>
            <Menu /> компонент II
           <Map /> компонент I 
      </Content>
</Layout>

Мотивация
Одна из важных страниц нашего приложения

Критерии приемки
Создана страница с вышеописанными условиями

Планируемое время работы
3 часа

**Comment by mkonevgit** [comment]
Функционал реализован в тикете 100

**Comment by mkonevgit** [comment]
В тикете 100 создана страница, включающая в себя карту и меню. Для страницы создан отдельный роут
