### ISSUE TITLE
Создать компонент LocationMenu.tsx I

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_front#99]
Задача
1. В папке pages > Location> создаем папку components (если еще не создана) > далее папку нашего компонента LocationMenu> и там уже LocationMenu.tsx и LocationMenu.scss (стараемся меньше inline стилей и больше записывать их в scss файл)
2. Структура меню
![30](https://user-images.githubusercontent.com/70585151/125194195-1916b600-e272-11eb-8396-1fc9226e8468.png)

3. Кнопка "список" ведется на страницу /location/list (где представлены страницы в виде списка)
4. Кнопка "стать инвестором" будет везде (путь еще не определен) либо в личный кабинет либо сразу на форму где предлагают стать инвестором

Вопросы, которые нужно обсудить с ментором 13.07:
1. Нужно ли вообще меню, либо мы можем оставить 2 кнопки (что сильно бы облегчило работу, меню служит для фильтрации выводимых кемпинг зон на карте

Мотивация
Важный элемент страницы location

Критерии приемки
Пока вопрос в обсуждении

Планируемое время работы
2 часа

**Comment by mkonevgit** [comment]
Функционал реализован в тикете 100

**Comment by mkonevgit** [comment]
В тикете 100 создана страница, включающая в себя карту и меню. Для страницы создан отдельный роут
